### ISSUE TITLE
Wes: Angular Todo HW

### ISSUE THREAD

**Issue by wesareed** [ga-wdi-exercises/angular_todo#39]
I created a repo from scratch rather than forking this one: 

repo link: https://github.com/wesareed/todo_angular

comfort_level: 4
completeness: 4

Comments:
Cannot get edit functionality working. Would love to get that wired up! Javascript taste like a rotten sour lime and Rails like a sweet sweet mango.

**Comment by adambray** [comment]
👍  on your app. Main suggestion is to avoid use of `$scope` in favor of `this.todos` style approach. It's more modern and encouraged in most style guides.
